version: '3.8'

services:
  app:
    container_name: vacancy_analysis
    build: ./
    depends_on:
      - db
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000'
    volumes:
      - ./app:/src/app
    ports:
      - ${APP_HOST_PORT}:8000
    restart: always
    env_file:
      - .env
  db:
    container_name: vacancy_analysis_postgres
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    ports:
      - ${POSTGRES_DB_HOST_PORT}:5432
    volumes:
      - .postgres:/var/lib/postgres/data
    restart: always
    env_file:
      - .env
